apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: "18.10.0" # adjust as needed
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: keycloak
  values:
    replicaCount: 1
    keycloak:
      username: admin
      password: adminpassword
    service:
      type: LoadBalancer